[program:equiva]
command=/var/www/equiva/venv/bin/gunicorn -w 3 -b 127.0.0.1:8000 app:app
directory=/var/www/equiva
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/equiva.log
stderr_logfile=/var/log/supervisor/equiva-error.log
environment=FLASK_ENV="production"
